new task pipeline
sariya23/go_tasks pull request #3
Opened 2024-11-18 05:10 UTC by sariya23

2024-11-25 12:17 UTC, mistandok commented
Попробую сначала сам решить, потом поревьюю твое решение

2024-11-25 12:19 UTC, mistandok commented
Давай в будущем задачи добавлять отдельно, а решения отдельно? чтобы можно было задачи вмерджить без решений и можно было параллельно думать

2024-11-25 12:24 UTC, sariya23 commented
> Давай в будущем задачи добавлять отдельно, а решения отдельно? чтобы можно было задачи вмерджить без решений и можно было параллельно думать

Да, хорошая идея

2024-11-26 07:58 UTC, mistandok requested changes

2024-11-26 07:58 UTC, mistandok commented on concurrency/task_create_pipeline/solution1/main.go
> +		for task := range in {
issue (blocking): у тебя тут цикл через каналы реализован, по сути. Ты в цикле в build добавляешь задачи, потом тут последовательно их вычитываешь и обрабатываешь, потом в следующем шаге также последовательно их вычитываешь и обрабатываешь.
Задачи в пайплайне на каждом шаге должны запускаться параллельно, последовательность тут идет в разрезе шагов. 

Условно у нас есть вот такие шаги:
```go
   step_1 ---------------> step_2
[job1, job1]              [job2, job2]
```

и получается так, что на каждом шаге job1 и job1  будут у тебя последовательно выполнятся, а должны параллельно. Последовательно должны выполняться job1 и job2

Давай этот PR отменим, добавишь просто пр с задачей и параллельно порешаем, посмотрим. И уже в следующих PR будем именно решение добавлять.

2024-11-26 18:52 UTC, sariya23 commented on concurrency/task_create_pipeline/solution1/main.go
> +		for task := range in {
Не очень  тебя понял. Я делал по примеру паттера
![image](https://github.com/user-attachments/assets/cda3bd4f-e51b-489b-b7b1-d9680d241af1)

2024-11-26 20:02 UTC, mistandok approved these changes

2024-11-26 20:05 UTC, merged